title: Mark Bauer
logo: "/images/mark-headshot.png?raw=true"
description: > 
  <br><br>
  Data Scientist.
  <br><br>
  I'm deeply passionate about applying data science and data engineering to foster innovation across various domains, 
  including climate risk, property intelligence, insurance, and commercial real estate. In addition to my professional pursuits, 
  I dedicate many weekends to contributing to open source projects, which collectively have earned over 250 stars on GitHub.
  <br><br>
  I hold a bachelor's and master's degree from Rutgers University specializing in Geographic Information Systems (GIS),
  along with an Advanced Graduate Certificate from New York University in Applied Urban Science and Informatics.
  <br><br>
  I'm best reached via <a href="https://www.linkedin.com/in/markebauer/">LinkedIn</a>, and you can explore my code on <a href="https://github.com/mebauer">GitHub</a>.
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-9ZBJ1XN9E6
