title: Mark Bauer
logo: "/images/mark-headshot.jpg?raw=true"
description: > 
  <br><br>
  Data Scientist.
  <br><br>
   I love all things data and open source. Interested in flood risk management. 
  <br><br>
  <a href="https://www.linkedin.com/in/markebauer/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-9ZBJ1XN9E6
